### ISSUE TITLE
No longer works properly in Android browsers

### ISSUE THREAD

**Issue by johnbacon** [jessepollak/card#199]
Hey Jesse – we've run into an issue that has put a major snafu into our mobile checkout pages.

It appears that mobile Android browsers (we've tested Firefox, Chrome, and the standard Android browser on two Galaxy S5s and one Galaxy S6) no longer format or validate inputs properly. This occurs on both your demo page and within our site's implementation. We are able to input unlimited digits in the credit card number field, the expiration date field does not format properly (with the slash), the CVC number allows infinite digits, etc.

It still works as expected on the two iOS devices we tested (both Safari and Chrome).

An interesting find: when remote debugging via Chrome, inputting the values into the phone via desktop keyboard causes the inputs to behave as expected (formatting/input of slash/etc.), but the inputs still don't work when inputting text via the phone's keyboard.

We received our first call about this issue yesterday, but it may have been occurring for much longer than that.

**Comment by jessepollak** [comment]
thanks for the report John! do you see any javascript errors in the
console? I can try and take a look this weekend!

**Comment by johnbacon** [comment]
Hi Jesse – no console errors present! Originally we thought it might be due to an initialization issue on mobile browsers, so we began remote debugging, and saw no errors thrown in the network tab or console.

Thanks for hopping on this! If there's anything we can do to help, please let us know.

**Comment by feliperaul** [comment]
Can someone else confirm this is actually happening ?

**Comment by theopolisme** [comment]
We are also encountering this error in production. We have received multiple user reports about the issue, but no console errors are being thrown/reported in our logging systems.

I can confirm that both the expiration field and CVC field appear to not be restricted at all (I can type any text). The credit card field is still formatting properly, though. Will be investigating further and will report anything else we can figure out...

**Comment by jessepollak** [comment]
Awesome, thanks! Any insight into what exactly is breaking would be really
useful.

**Comment by theopolisme** [comment]
Looking through the other open issues, similar to #196? I wasn't able to delve into this today but will look tomorrow.

**Comment by michaelblinn** [comment]
Also seeing this issue on mobile android / chrome. We have a test at http://test.giv2giv.org/widget/example.html

**Comment by poacher2k** [comment]
Also experiencing this in Version/4.0 Chrome/30.0.0.0. No errors in console, even with debug enabled.

**Comment by poacher2k** [comment]
Seems like the cause of this is two things.
1. the `keypress` event does not get fired at all
2. `keyCode` / `which` is always `0`

**Comment by MouseEatsCat** [comment]
This could be an issue with <input type="text"> and the way Android Keyboards interact with it. I solved this issue by replacing the input fields that should be numbers with <input type="tel">.

This changes the keyboard to a numbers-only keyboard and the formatting seems to work the way it's supposed to.

**Comment by gauravshegokar** [comment]
working on android devices with <input type="tel"> instead of <input type="text">

**Comment by poacher2k** [comment]
@gauravshegokar: nice workaround! works in Chrome 30 on android for me now.

**Comment by nuschk** [comment]
Any news on this? I have the same problem and the workaround isn't working in Chrom 0.49. Any help greatly appreciated.

**Comment by jessepollak** [comment]
Hi — does anyone have a reproduction case of this? Thanks!

**Comment by theopolisme** [comment]
I just verified on my Nexus 6P running the latest version of Chrome that your [own demo page](http://jessepollak.github.io/card/) is susceptible, as is the [test case](http://test.giv2giv.org/widget/example.html) that @michaelblinn shared in October. To reproduce, try typing any text into the expiry and CVV fields. You'll note that the text in the fields in neither auto-formatted nor is character entry restricted.

Glad to see you're looking into this!

![screenshot_20160423-155025](https://cloud.githubusercontent.com/assets/1410202/14763924/352258e4-096b-11e6-80e0-7cb294cbb2b9.png)

![screenshot_20160423-154636](https://cloud.githubusercontent.com/assets/1410202/14763913/9c99e0f6-096a-11e6-9864-380d2d38e591.png)

**Comment by seglavi** [comment]
hi,
i am facing this problem as well.
is anyone can solve this issue?

thanks.

**Comment by nuschk** [comment]
We didn't solve it exactly, but got it working with the following steps (we use react FWIW):

- Validate and format the fields with your own onchange handlers (we're using our own formatters, but I think you might also use the Payments library, which is used by cardjs as well). This will make the widget work, but the card type isn't correctly displayed.
- Fire a CustomEvent when the number field changes. This will be caught by cardjs and the card type will be adjusted accordingly.

The code for the latter is something along theses lines:


    try {
      const cardType = Payment.fns.cardType(formattedNumber);
      const ev = new CustomEvent('payment.cardType', { detail: cardType });
      myNumberInputField.dispatchEvent(ev);
    } catch (exception) {  
       // silently swallow IE11 exceptions
    }

As you can see, this doesn't work for IE11. I didn't have the time to make it work there, as the widget is essentially working without it.

We do this on all devices btw, it doesn't seem to do harm in desktop environments.

This is really hacky, so use at own risk. We use it in production though.

**Comment by seglavi** [comment]
Thank you for your answer and time.

In fact changing type text to tel is working in some phones. But strangely not working still for some phones like Galaxy Note series etc.

Hope can find a deep solution to this.

**Comment by wbhob** [comment]
I can verify that this is still an issue. When will it be fixed?

**Comment by coolirisroto** [comment]
Then ?

**Comment by wbhob** [comment]
I DM'd Jesse on twitter, he said he doesn't have time to fix this, and is asking for a PR.

**Comment by malithmcr** [comment]
Problem is on  keypress is not supporting android os. 
I fixed it like this : 
 var ua = navigator.userAgent.toLowerCase();
            var isAndroid = ua.indexOf("android") > -1; //&& ua.indexOf("mobile");
            if(isAndroid) {
                $("#expiry").on('keyup', function(e) {
                    var target = $("#expiry"),
                        val = target.val();
                    if (/^\d$/.test(val) && val !== '0' && val !== '1') {
                        target.val( "0" + val + " / ");
                        $('.clear-input-android').show().click(function () {
                            target.val("");
                        })
                    } else if (/^\d\d$/.test(val)) {
                        target.val( val + " / ");
                        $('.clear-input-android').show().click(function () {
                            target.val("");
                        })
                    }
                });
            }

**Comment by wbhob** [comment]
You can/should PR that into the main library

**Comment by flavaflav** [comment]
I've a little patch and now it works on Android. Tested against Android (Chrome), Safari (iOS), Chrome (Windows) and Microsoft Edge.

[https://www.diffchecker.com/AzBiDqiZ](url)

**Comment by OzgunAkkoyun** [comment]
> working on android devices with input type="tel" instead of input type="text"

Its working to me too! thanks:D

**Comment by brittonk** [comment]
Did anyone ever fix this? As of 12/25/2018 it is still not working on a great many levels for older android phones.

**Comment by imgom3s** [comment]
for me the problem solved by setting all numeric fields type="tel"

**Comment by jorgecarrillo27** [comment]
Works

This could be an issue with <input type="text"> and the way Android Keyboards interact with it. I solved this issue by replacing the input fields that should be numbers with <input type="tel">

This changes the keyboard to a numbers-only keyboard and the formatting seems to work the way it's supposed to.

**Comment by melloware** [comment]
Workaround provided for Android closing ticket.

**Comment by melloware** [comment]
I believe instead of `type="tel"` you should be able to use HTML5 `inputmode` which tells which vritual keyboard to use in mobile browsers.  So `<input type="text" inputmode="numeric" />`
